version: "2"
services:
  app:
    image: npm-react-app
    build: .
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./:/home/node/app
      - react-modules:/home/node/app/node_modules
volumes: 
  react-modules:
